---
title: "Visualizing Electricity Consumption & Occupancy (ECO)"
author: "Chevy Robertson"
date: "10/25/2021"
output: html_document
---



## Introduction

For this assignment, the aim was to use a data set to produce interactive visualizations that attempt to answer questions about the data. The data set in question represents a fraction of the ECO data set. The ECO data set was collected as part of the process in carrying out a project called "Smart Meter Services" that was undertaken by the Distributed Systems Group a little over 5 years ago. The data contain statistics on electricity consumption and occupancy at one-second time intervals for six different Swiss households for over a period of more than half a year. In this smaller portion, only data for three of these households are available. Upon exploration of the data, two questions arose:

1. For a particular household appliance, is there any observable trend for how the electricity consumption changes, on average, from hour to hour each day?

2. With regard to both individual and all household appliances, how does average electricity consumption change across the days of a week?

Below, a rationale is given for the data pre-processing steps and visualization design decisions that were made in an effort to answer these questions.



## Rationale

Before either visual was drafted, the data needed to be transformed into a representation more conducive for analysis. Since either question involved analyzing information at the appliance level, for each appliance of each household, data that contained power consumption measurements at each second was read in. Therefore, to be able to understand how the data change over much longer time intervals, variables were added to each data set that recorded the day and hour at which each measurement occurred. Then, considering negative electricity consumption values are nonsensical, any rows with measurements less than zero were filtered out of each data set. To produce average metrics, the next step in transforming the data involved creating two new data sets from each appliance-household combination: one for recording average consumption for a particular hour, and another for recording average consumption for a particular day of the week. In alignment with this operation, new data sets were formed by grouping each old one by the hour of the day and computing the average electricity consumption. Similarly, the second new version of the old data sets were formed by grouping by the day of the week. At this point, everything was in place to combine all of the data to form two final data sets: one with information at the hourly level, and another with information at the daily level.

To visualize how the average hourly electric consumption changed for each appliance, the first instinct was to chart a time series of each measurement per hour. However, it was discovered that making a time series animate is actually quite complicated. This discovery prompted the decision to use a bar chart geometry instead to showcase the raw consumption value of each appliance, and a slider to allow someone to visualize the vertical increases and decreases in the bars (and thus the power) over time. To graph this representation appropriately, the x-axis was chosen to contain a bar for each appliance, and the y-axis was chosen to record the average power consumption (in Watts) for each appliance. In addition, a categorical color scheme and x-axis labels were added with the intent of allowing a user to more clearly identify each appliance. In case a user became interested in knowing the actual values, rather than just estimating using the height of each bar, a tooltip was included as well to show the appliance and time of day for each power measurement. Lastly, features were included in the visualization to allow a user to further interact and explore the data set. These included options to zoom, pan, and select specific portions of the data to observe.

Due to the nature of the second question, the design decisions in drafting the second interactive visualization were slightly different. Like the first visualization, the purpose for creating the chart was to allow a user to view how the data change over time for each appliance. However, unlike the first visualization, the goal was to also illustrate the more general pattern of the aggregation of these appliances. Consequently, a stacked area plot was chosen for the overall geometry of the second interactive visualization. In doing so, this accomplished three goals: the lines between each stack were used to show change over time, each stack was used to identify a particular appliance, and the total of all the stacks was used to address how overall consumption changes from one day to the next. To better showcase the trends, each position on the x-axis contained a day of the week, and the y-axis measured the average power consumption. Just like the first plot, color was used a visual encoding to make the distinction between each appliance, and a tooltip was included to show the specific average power measurement with regard to any possible combination of day and appliance.
    


## Visuals

Average electric consumption changes at the hourly level can be explored by navigating to the "Plotly" page of the website. On the other hand, if one is more interested in exploring changes at the day-level, this can be explored by navigating to the "Altair" page of the website.



# Sources

Wilhelm Kleiminger, Christian Beckel, Silvia Santini.
Household Occupancy Monitoring Using Electricity Meters.
Proceedings of the 2015 ACM International Joint Conference on Pervasive and Ubiquitous Computing (UbiComp 2015). Osaka, Japan, September 2015.

Christian Beckel, Wilhelm Kleiminger, Romano Cicchetti, Thorsten Staake, and Silvia Santini.
The ECO Data Set and the Performance of Non-Intrusive Load Monitoring Algorithms.
Proceedings of the 1st ACM International Conference on Embedded Systems for Energy-Efficient Buildings (BuildSys 2014). Memphis, TN, USA. ACM, November 2014.


